### ISSUE TITLE
Automatic enqueuing of first job

### ISSUE THREAD

**Issue by ramontayag** [arturictus/sidekiq_alive#2]
What do you think about `SidekiqAlive.start` automatically queuing that first job, if it needs to?

**Comment by arturictus** [comment]
Hi @ramontayag,
I think it would be a nice improvement. But we should check first if there is an existing one scheduled or in queue.
If not every time sidekiq restarts will queue duplicated jobs.

**Comment by ramontayag** [comment]
@arturictus could we just check to see if the liveness key is set? If it is, it doesn't enqueue it. If not set, it enqueues the job.

**Comment by arturictus** [comment]
Hi @ramontayag ,
There is a discussion on #3 that could fix this issue.
If you want to check it and see if it will fit your needs.

**Comment by arturictus** [comment]
@ramontayag, New version released.
check it out!.
Thanks for the help

**Comment by ramontayag** [comment]
@arturictus not sure I understand. https://github.com/arturictus/sidekiq_alive/pull/3 hasn't been merged?

**Comment by arturictus** [comment]
Hi @ramontayag,
I cherry picked the your sinatra commits.
I implemented in different way. If you check the discussion in #3 you will see why.
In the implementation in last version are working the features you proposed in #3.
now:
- Each replica auto evaluates itself without having to stop all the replicas because one stoped
- First job it's enqueued on when sidekiq starts

**Comment by ramontayag** [comment]
I see why. Thanks for the explanation!
