### ISSUE TITLE
Running with Sidekiqswarm

### ISSUE THREAD

**Issue by geoffharcourt** [arturictus/sidekiq_alive#66]
Hi! This is a great gem, thank you for your work on it.

We are trying out Sidekiqswarm and it appears that when run with sidekiq_alive, there's one exception per worker process after the first one as each process attempts to bind to the port. Is there a way to only have one web server boot or to have different ports get assigned to each worker process?

**Comment by arturictus** [comment]
Hi @geoffharcourt,
That's an interesting problem to solve :).
I would have to investigate the issue further to give you a better response, and since I do not use Sidekiq enterprise is hard for me to test.

But as a quick answer I can imagine few solutions:

a) Not run the HTTP server and execute a ruby **script to ask redis**, that would imply
 - option to not start the server
 - script to connect to redis and query the key, exit 1 if there is no key
 - pass all the required ENV variables to the script
 - execute in the LivenessProbe that script
 - 
b) run Http Server in an indepent pod and script to request that pod


Any other solutions that you can think of?

**Comment by geoffharcourt** [comment]
Hey @arturictus we're still thinking through what we'd want to do here.

**Comment by jwhitcraft** [comment]
@geoffharcourt did you ever figure this one out?

**Comment by geoffharcourt** [comment]
We are using Sidekiq Enterprise's built-in healthcheck now.
